public class Street {
    String name = "";
    int streetID = 0;
    int value = 0;
    int group = 0;
    int mortgage = 0;
    int serverPrice = 0;
    int amountOfServers = 0;
    boolean datacenterExistent = false;
    int undeveloped = 0;
    int server1 = 0;
    int server2 = 0;
    int server3 = 0;
    int server4 = 0;
    int datacenter = 0;
    int owner = 0;
    boolean buyable = true;
    boolean mortgaged = false;
}
